DROP TABLE LECTURE;
DROP TABLE ENROLL;
DROP TABLE COURSE;
DROP TABLE PROFESSOR;
DROP TABLE STUDENT;

CREATE TABLE STUDENT(
    STU_NO     VARCHAR2(5 BYTE)  NOT NULL,
    STU_NAME   VARCHAR2(15 BYTE) NULL,
    STU_ADR    VARCHAR2(20 BYTE) NULL,
    STU_CLASS  NUMBER(1)         NULL,
    STU_CHAPRO CHAR(13 BYTE)     NULL
);

CREATE TABLE PROFESSOR(
    PRO_NO    VARCHAR2(5 BYTE)  NOT NULL,
    PRO_NAME  VARCHAR2(15 BYTE) NULL,
    PRO_MAJOR VARCHAR2(20 BYTE) NULL
);

CREATE TABLE COURSE(
    COURSE_NO   NUMBER            NOT NULL,
    COURSE_NAME VARCHAR2(30 BYTE) NULL,
    GRADE       VARCHAR2(3 BYTE)  NULL
);

CREATE TABLE ENROLL(
    ENROLL_NO NUMBER           NOT NULL,
    STU_NO    VARCHAR2(5 BYTE) NOT NULL,
    COURSE_NO NUMBER           NOT NULL,
    APP_DATE  DATE             NULL
);

CREATE TABLE LECTURE(
    LEC_NO    VARCHAR2(5 BYTE) NOT NULL,
    PRO_NO    VARCHAR2(5 BYTE) NOT NULL,
    ENROLL_NO NUMBER           NOT NULL, 
    LEC_NAME  VARCHAR2(30 BYTE)    NULL,
    LEC_ROOM  VARCHAR2(30 BYTE)    NULL
);

ALTER TABLE STUDENT
    ADD CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO);
ALTER TABLE PROFESSOR
    ADD CONSTRAINT PK_PORFESSOR PRIMARY KEY(PRO_NO);
ALTER TABLE COURSE
    ADD CONSTRAINT PK_COURSE PRIMARY KEY(COURSE_NO);
ALTER TABLE ENROLL
    ADD CONSTRAINT PK_ENROLL PRIMARY KEY(ENROLL_NO);
ALTER TABLE LECTURE
    ADD CONSTRAINT PK_LECTURE PRIMARY KEY(LEC_NO);
    
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENROLL_COURSE FOREIGN KEY(COURSE_NO)
        REFERENCES COURSE(COURSE_NO)
             ON DELETE CASCADE;
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY(STU_NO)
        REFERENCES STUDENT(STU_NO)
             ON DELETE CASCADE;
ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LECTURE_PROFESSOR FOREIGN KEY(PRO_NO)
        REFERENCES PROFESSOR(PRO_NO)
             ON DELETE CASCADE;
ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LECTURE_ENROLL FOREIGN KEY(ENROLL_NO)
        REFERENCES ENROLL(ENROLL_NO)
            ON DELETE CASCADE;