-- 테이블 삭제
DROP TABLE ORDERS;
DROP TABLE CUSTOMERS;
DROP TABLE PRODUCTS;

-- PRODUCTS 테이블 생성
CREATE TABLE PRODUCTS(
    PRODUCT_NO    NUMBER             NOT NULL,
    PRODUCT_NAME  VARCHAR2(100 BYTE) NOT NULL,
    PRODUCT_PRICE NUMBER             NULL,
    PRODUCT_IMAGE VARCHAR2(300 BYTE) NULL
);
   
-- CUSTOMERS 테이블 생성 
CREATE TABLE CUSTOMERS(
    CUSTOMER_NO    NUMBER            NOT NULL,
    CUSTOMER_ID    VARCHAR2(30 BYTE) NOT NULL,
    CUSTOMER_NAME  VARCHAR2(30 BYTE) NULL,
    CUSTOMER_PHONE VARCHAR2(15 BYTE) NULL
);

-- ORDERS 테이블 생성 
CREATE TABLE ORDERS(
    ORDER_NO     NUMBER NOT NULL,
    CUSTOMER_NO  NUMBER NOT NULL,
    PRODUCT_NO   NUMBER NOT NULL,
    ORDER_AMOUNT NUMBER NULL
);

-- 기본키 설정
ALTER TABLE PRODUCTS ADD CONSTRAINT PRODUCT_PK PRIMARY KEY(PRODUCT_NO);
ALTER TABLE CUSTOMERS  ADD CONSTRAINT CUSTOMER_PK  PRIMARY KEY(CUSTOMER_NO);
ALTER TABLE ORDERS ADD CONSTRAINT ORDER_PK PRIMARY KEY(ORDER_NO);

-- UNIQUE 설정
ALTER TABLE CUSTOMERS  ADD CONSTRAINT CUSTOMER_ID_UQ  UNIQUE(CUSTOMER_ID);

-- 외래키 설정
ALTER TABLE ORDERS
    ADD CONSTRAINT ORDER_CUSTOMER_FK FOREIGN KEY(CUSTOMER_NO)
        REFERENCES CUSTOMERS(CUSTOMER_NO);
ALTER TABLE ORDERS
    ADD CONSTRAINT ORDER_PRODUCT_FK FOREIGN KEY(PRODUCT_NO)
        REFERENCES PRODUCTS(PRODUCT_NO);