# serer.port
# web.xml
#server.servlet.encoding.charset=UTF-8
#server.servlet.encoding.enabled=true
# server.servlet.encoding.force=true  
# session 1800 seconds = 30 minute
#database.connection
server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 1800

#database.connection
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      jdbc-url: jdbc:oracle:thin:@localhost:1521:xe
      username: scott
      password: TIGER

# mybatis
mybatis:
  config-location: mybatis/config/mybatis-config.xml
  mapper-locations: mybatis/mapper/*.xml
