-- 다중 첨부

DROP TABLE ATTACH;
CREATE TABLE ATTACH
(
    ATTACH_NO NUMBER NOT NULL,  -- PK
    PATH VARCHAR2(300 BYTE),
    ORIGIN VARCHAR2(300 BYTE),
    FILESYSTEM VARCHAR2(40 BYTE),
    DOWNLOAD_CNT NUMBER,
    UPLOAD_NO NUMBER  -- FK
);

DROP TABLE UPLOAD;
CREATE TABLE UPLOAD
(
    UPLOAD_NO NUMBER NOT NULL,  -- PK
    TITLE VARCHAR2(100 BYTE),
    CONTENT VARCHAR2(100 BYTE),
    CREATE_DATE TIMESTAMP,
    MODIFY_DATE TIMESTAMP
);
-- 기본키
ALTER TABLE ATTACH
    ADD CONSTRAINT ATTACH_PK
        PRIMARY KEY(ATTACH_NO);
ALTER TABLE UPLOAD
    ADD CONSTRAINT UPLOAD_PK
        PRIMARY KEY(UPLOAD_NO);

-- 외래키
ALTER TABLE ATTACH
    ADD CONSTRAINT ATTACH_UPLOAD_FK
        FOREIGN KEY(UPLOAD_NO) REFERENCES UPLOAD(UPLOAD_NO)
            ON DELETE CASCADE;  -- 업로드 내역을 삭제하면 첨부 내역이 함께 삭제되는 옵션

-- 시퀀스
DROP SEQUENCE UPLOAD_SEQ;
CREATE SEQUENCE UPLOAD_SEQ NOCACHE;
DROP SEQUENCE ATTACH_SEQ;
CREATE SEQUENCE ATTACH_SEQ NOCACHE;