-- 시퀀스
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;

-- 테이블
DROP TABLE BOARD;
CREATE TABLE BOARD(
    BOARD_NO NUMBER NOT NULL,
    WRITER   VARCHAR2(100 BYTE),
    TITLE    VARCHAR2(100 BYTE) NOT NULL,
    CREATE_DATE DATE,
    CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NO)
);

-- 행
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '뽀로로', '노는게 제일 좋아', SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '친구들', '모여라', SYSDATE);
COMMIT;


